Repository WildCodeSchool/202302-orleans-php-project2-amibeauceron, pull requests merged in 2023-05, with the labels that each got.

#44 remise en place de la table user supprimée de database
  database.sql
Labels: REVIEWED

#47 fix login form height too big
  public/assets/css/login.css
  src/View/Login/login.html.twig
Labels: REVIEWED

#45 S03U40 intégration de l'upload dans la partie Edition des actualités
  public/assets/css/admin.css
  src/Controller/AdminActualityController.php
  src/Model/ActualityManager.php
  src/View/Admin/Actuality/_form.html.twig
  src/View/Admin/Actuality/edit.html.twig
  src/View/Admin/Actuality/index.html.twig
Labels: REVIEWED

#35 S03 us12 add event
  src/Controller/AdminEventController.php
  src/Model/EventManager.php
  src/View/Admin/Actuality/_form.html.twig
  src/View/Admin/Event/add.html.twig
  src/View/Admin/index.html.twig
  src/routes.php
Labels: CONFLICTS RESOLVED

#48 form admin
  public/assets/css/admin.css
  src/View/Admin/Actuality/add.html.twig
Labels: CONFLICTS RESOLVED

#49 S04U50 visiteurs consultent les mises en relations chiens du club
  data_migration/dog-1.jpg
  data_migration/dog-2.jpg
  database.sql
  public/assets/css/dogs-relation.css
  src/Controller/DogController.php
  src/Model/DogManager.php
  src/View/Component/_card_dog_relation.html.twig
  src/View/Component/_navbar.html.twig
  src/View/Relation/index.html.twig
  src/routes.php
Labels: REVIEWED, CONFLICTS RESOLVED

#54 fix_style
  public/assets/css/dogs-relation.css
Labels: REVIEWED

#56 fix suppression page accueil admin
  src/View/Admin/index.html.twig
Labels: REVIEWED

#53 S04 us19 membres admin add
  database.sql
  src/Controller/AdminMemberController.php
  src/Model/MemberManager.php
  src/View/Admin/Member/add.html.twig
  src/View/Admin/Member/index.html.twig
  src/View/Component/_errors.html.twig
  src/routes.php
Labels: REVIEWED, CONFLICTS RESOLVED

#60 fix route dog
  src/routes.php
Labels: REVIEWED

#55 finish update
  database.sql
  src/Controller/AdminEventController.php
  src/Model/EventManager.php
  src/View/Admin/Event/_form.html.twig
  src/View/Admin/Event/update.html.twig
  src/routes.php
Labels: REVIEWED, CONFLICTS RESOLVED

#63 Fix nav bar admin height
  public/assets/css/admin.css
Labels: REVIEWED

#68 fix style home actuality
  public/assets/css/actuality_small.css
Labels: REVIEWED

#61 S04U49 Suppression d'une fiche chien coté admin
  src/Controller/AdminDogController.php
  src/View/Admin/Relation/index.html.twig
  src/View/Component/Admin/_navbar.html.twig
  src/routes.php
Labels: REVIEWED

#65 S04U54 Intégration du controle d'accès pour l'administrateur sur les pages d'administration
  src/Controller/AbstractAdminController.php
  src/Controller/Admin/AdminController.php
  src/Controller/AdminActualityController.php
  src/Controller/AdminDogController.php
  src/Controller/AdminEventController.php
  src/Controller/AdminMemberController.php
Labels: REVIEWED

#67 fix navbar menu - sort du bandeau quand version mobil
  public/assets/css/navbar.css
Labels: REVIEWED

#64 S04U52 Ajouter filtre is_lof sur la page de visualisation des chiens
  public/assets/css/dogs-relation.css
  src/Controller/DogController.php
  src/Model/DogManager.php
  src/View/Relation/index.html.twig
Labels: REVIEWED

#69 delete part
  src/Controller/AdminEventController.php
  src/routes.php
Labels: CONFLICTS RESOLVED

#51 list event ok
  src/Controller/AdminEventController.php
  src/View/Admin/Event/index.html.twig
  src/routes.php
Labels: CONFLICTS RESOLVED

#59 S04U48 Ajouter une fiche chiens côté admin.
  database.sql
  public/assets/css/admin.css
  src/Controller/AdminDogController.php
  src/Model/DogManager.php
  src/View/Admin/Relation/_form.html.twig
  src/View/Admin/Relation/add.html.twig
  src/View/Component/_card_dog_relation.html.twig
  src/routes.php
Labels: REVIEWED, CONFLICTS RESOLVED

#72 fix route nos chiens
  src/View/Component/_navbar.html.twig
Labels: REVIEWED

#73 fix H1 et H2 too big
  public/assets/css/style.css
Labels: REVIEWED

#74 fix title camelcase
  public/assets/css/dogs-relation.css
  public/assets/css/member.css
  src/View/Beauceron/beauceron.html.twig
  src/View/Care/index.html.twig
  src/View/Event/event.html.twig
  src/View/Member/index.html.twig
Labels: REVIEWED

#62 S04U51 Édition d'une fiche chien côté admin
  src/Controller/AdminDogController.php
  src/Model/DogManager.php
  src/View/Admin/Relation/edit.html.twig
  src/View/Admin/Relation/index.html.twig
  src/routes.php
Labels: REVIEWED, CONFLICTS RESOLVED

#75 dev to main
  public/assets/css/dogs-relation.css
  public/assets/css/member.css
  public/assets/css/style.css
  src/Controller/AdminDogController.php
  src/Model/DogManager.php
  src/View/Admin/Relation/edit.html.twig
  src/View/Admin/Relation/index.html.twig
  src/View/Beauceron/beauceron.html.twig
  src/View/Care/index.html.twig
  src/View/Component/_navbar.html.twig
  src/View/Event/event.html.twig
  src/View/Member/index.html.twig
  src/routes.php
Labels: REVIEWED

#71 S04 us21 membres admin edit
  src/Controller/AdminMemberController.php
  src/Model/MemberManager.php
  src/View/Admin/Member/index.html.twig
  src/View/Admin/Member/update.html.twig
  src/routes.php
Labels: REVIEWED, CONFLICTS RESOLVED

#76 fix bad caracrtères to view
  src/View/Admin/Relation/index.html.twig
Labels: REVIEWED

#77 reviewed beauceron
  public/assets/css/caractere.css
  public/assets/css/genese.css
  public/assets/css/history.css
  src/View/Beauceron/beauceron.html.twig
  src/View/Beauceron/beauceron_caractere.html.twig
  src/View/Beauceron/beauceron_genese.html.twig
Labels: REVIEWED

#78 fix column button admin actuality
  public/assets/css/admin.css
  src/View/Admin/Actuality/index.html.twig
Labels: REVIEWED

#79 fix style et mise en page dog card and actuality card
  public/assets/css/actuality_small.css
  public/assets/css/dogs-relation.css
  src/View/Component/_card_dog_relation.html.twig
Labels: REVIEWED

#80 Dev to main
  public/assets/css/actuality_small.css
  public/assets/css/admin.css
  public/assets/css/caractere.css
  public/assets/css/dogs-relation.css
  public/assets/css/genese.css
  public/assets/css/history.css
  src/Controller/AdminMemberController.php
  src/Model/MemberManager.php
  src/View/Admin/Actuality/index.html.twig
  src/View/Admin/Member/index.html.twig
  src/View/Admin/Member/update.html.twig
  src/View/Admin/Relation/index.html.twig
  src/View/Beauceron/beauceron.html.twig
  src/View/Beauceron/beauceron_caractere.html.twig
  src/View/Beauceron/beauceron_genese.html.twig
  src/View/Component/_card_dog_relation.html.twig
  src/routes.php
Labels: REVIEWED

#81 fix style login height
  public/assets/css/login.css
  public/assets/css/style.css
Labels: REVIEWED

#82 fix style admin table
  public/assets/css/admin.css
  src/View/Admin/Actuality/index.html.twig
  src/View/Admin/Relation/index.html.twig
Labels: REVIEWED

#83 Membres admin delete + uploads
  data_migration/jonsnow.jpg
  data_migration/michaelscofield.jpg
  data_migration/walterwhite.jpg
  database.sql
  src/Controller/AdminMemberController.php
  src/Model/MemberManager.php
  src/View/Component/_card_member.html.twig
  src/routes.php
Labels: REVIEWED

#85 fix evenement
  src/Controller/AdminEventController.php
  src/Model/EventManager.php
  src/View/Admin/Event/_form.html.twig
  src/View/Admin/Event/add.html.twig
  src/View/Admin/Event/index.html.twig
  src/View/Admin/Event/update.html.twig
  src/routes.php
Labels: REVIEWED

#86 fix header style
  public/assets/css/member.css
  src/View/Member/index.html.twig
Labels: REVIEWED

#87 Dev To Main
  data_migration/jonsnow.jpg
  data_migration/michaelscofield.jpg
  data_migration/walterwhite.jpg
  database.sql
  public/assets/css/admin.css
  public/assets/css/login.css
  public/assets/css/member.css
  public/assets/css/style.css
  src/Controller/AdminEventController.php
  src/Controller/AdminMemberController.php
  src/Model/EventManager.php
  src/Model/MemberManager.php
  src/View/Admin/Actuality/index.html.twig
  src/View/Admin/Event/_form.html.twig
  src/View/Admin/Event/add.html.twig
  src/View/Admin/Event/index.html.twig
  src/View/Admin/Event/update.html.twig
  src/View/Admin/Member/index.html.twig
  src/View/Admin/Relation/index.html.twig
  src/View/Component/_card_member.html.twig
  src/View/Member/index.html.twig
  src/routes.php
Labels: REVIEWED

#96 add reame info
  README.md
Labels: REVIEWED

#103 uniformiser table admin
  public/assets/css/admin.css
  src/View/Admin/Actuality/index.html.twig
  src/View/Admin/Event/index.html.twig
  src/View/Admin/Member/index.html.twig
  src/View/Admin/Relation/index.html.twig
Labels: REVIEWED

#104 start fix beauceron
  public/assets/css/caractere.css
  public/assets/css/genese.css
  public/assets/css/history.css
  src/View/Admin/index.html.twig
  src/View/Beauceron/beauceron.html.twig
  src/View/Beauceron/beauceron_genese.html.twig
Labels: REVIEWED

#106 issues resolved
  public/assets/css/care.css
  public/assets/css/member.css
  public/assets/css/style.css
  src/Controller/AdminMemberController.php
  src/View/Admin/Member/index.html.twig
Labels: REVIEWED

#107 beauceron ok
  public/assets/css/caractere.css
  public/assets/css/genese.css
  public/assets/css/history.css
Labels: REVIEWED

#108 fix footer style response
  public/assets/css/footer.css
  src/View/Component/_footer.html.twig
Labels: REVIEWED

#109 dev to main
  README.md
  public/assets/css/admin.css
  public/assets/css/caractere.css
  public/assets/css/care.css
  public/assets/css/footer.css
  public/assets/css/genese.css
  public/assets/css/history.css
  public/assets/css/member.css
  public/assets/css/style.css
  src/Controller/AdminMemberController.php
  src/View/Admin/Actuality/index.html.twig
  src/View/Admin/Event/index.html.twig
  src/View/Admin/Member/index.html.twig
  src/View/Admin/Relation/index.html.twig
  src/View/Admin/index.html.twig
  src/View/Beauceron/beauceron.html.twig
  src/View/Beauceron/beauceron_genese.html.twig
  src/View/Component/Admin/_navbar.html.twig
  src/View/Component/_footer.html.twig
  src/View/Component/_navbar.html.twig
Labels: REVIEWED

#110 fix delete actu
  public/uploads/adhesion-association.jpg
  public/uploads/assemblee-generale.jpg
  src/Controller/AdminActualityController.php
  src/View/Actuality/show.html.twig
  src/routes.php
Labels: REVIEWED

#112 ok
  src/routes.php
Labels: REVIEWED

#111 evenement ok
  public/assets/css/event.css
  public/assets/js/event.js
Labels: REVIEWED

#113 fix card style
  public/assets/css/actuality.css
  public/assets/css/actuality_small.css
  public/assets/css/dogs-relation.css
  src/View/Component/_card_dog_relation.html.twig
Labels: REVIEWED

#114 finish finaly Beauceron page
  public/assets/css/caractere.css
  public/assets/css/genese.css
  public/assets/css/history.css
  src/View/Beauceron/beauceron.html.twig
  src/View/Beauceron/beauceron_caractere.html.twig
  src/View/Beauceron/beauceron_genese.html.twig
Labels: REVIEWED

#116 fix bug filter
  public/assets/css/dogs-relation.css
  src/Model/DogManager.php
Labels: REVIEWED

#117 fix back button card actuality
  public/assets/css/actuality.css
  src/View/Actuality/show.html.twig
Labels: REVIEWED

#120 Fix care
  public/assets/css/care.css
  src/View/Care/index.html.twig
Labels: REVIEWED

#121 Dev to main
  public/assets/css/actuality.css
  public/assets/css/actuality_small.css
  public/assets/css/caractere.css
  public/assets/css/care.css
  public/assets/css/dogs-relation.css
  public/assets/css/event.css
  public/assets/css/genese.css
  public/assets/css/history.css
  public/assets/css/login.css
  public/assets/css/member.css
  public/assets/js/event.js
  public/uploads/adhesion-association.jpg
  public/uploads/assemblee-generale.jpg
  src/Controller/AdminActualityController.php
  src/Model/DogManager.php
  src/View/Actuality/show.html.twig
  src/View/Beauceron/beauceron.html.twig
  src/View/Beauceron/beauceron_caractere.html.twig
  src/View/Beauceron/beauceron_genese.html.twig
  src/View/Care/index.html.twig
  src/View/Component/_card_dog_relation.html.twig
  src/routes.php
Labels: REVIEWED

#118 fix event ok
  data_migration/beer.png
  data_migration/chevalier.webp
  data_migration/cine.jpg
  data_migration/hotdogs.jpg
  database.sql
  public/assets/css/admin.css
  public/assets/css/event.css
  src/Controller/AdminEventController.php
  src/View/Admin/Event/index.html.twig
  src/View/Event/event.html.twig
Labels: REVIEWED

#124 ajout de 2 membres
  data_migration/DanieleRenaux.png
  data_migration/LeguedeDidier.png
  database.sql
Labels: REVIEWED

#126 remove block js
  src/View/Event/event.html.twig
Labels: REVIEWED

#128 fix login button to footer
  public/assets/css/footer.css
  src/View/Component/_footer.html.twig
  src/View/Home/index.html.twig
Labels: REVIEWED

#123 fix text database
  database.sql
Labels: CHANGES REQUESTED

#129 Dev to main
  data_migration/DanieleRenaux.png
  data_migration/LeguedeDidier.png
  data_migration/beer.png
  data_migration/chevalier.webp
  data_migration/cine.jpg
  data_migration/dog-3.jpeg
  data_migration/dog-5.jpg
  data_migration/hotdogs.jpg
  data_migration/poste_a_pourvoir.jpg
  database.sql
  public/assets/css/actuality.css
  public/assets/css/admin.css
  public/assets/css/event.css
  public/assets/css/footer.css
  public/assets/css/header.css
  src/Controller/AdminEventController.php
  src/View/Admin/Event/index.html.twig
  src/View/Component/_footer.html.twig
  src/View/Event/event.html.twig
  src/View/Home/index.html.twig
Labels: REVIEWED

#130 fix edition
  src/Controller/AdminDogController.php
Labels: REVIEWED

#131 Dev to main
  src/Controller/AdminDogController.php
Labels: REVIEWED
