Repository WildCodeSchool/202302-orleans-php-project2-amibeauceron, pull requests merged in 2023-04, with the labels that each got.

#3 S01U10-Création de la page News index
  database.sql
  public/assets/css/actuality.css
  public/assets/css/style.css
  public/assets/images/dog-information.webp
  public/assets/images/empreintechienblanc.png
  src/Controller/ActualityController.php
  src/Model/ActualityManager.php
  src/View/Actuality/index.html.twig
  src/View/Component/_card_actuality.html.twig
  src/View/base.html.twig
  src/routes.php
Labels: REVIEWED

#8 history
  public/assets/css/history.css
  public/assets/css/navbar.css
  public/assets/css/style.css
  public/assets/images/beauceron/img1.jpeg
  public/assets/images/beauceron/img2.jpg
  src/Controller/DogController.php
  src/View/Beauceron/beauceron.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: CONFLICTS

#20 fix route
  src/routes.php
Labels: REVIEWED

#9 Implementation des layouts pour la partie admin et visiteur avec la p…
  public/assets/css/admin.css
  public/assets/css/header.css
  public/assets/css/navbar.css
  public/assets/css/style.css
  public/assets/images/img_header_dog.jpg
  src/Controller/Admin/AdminController.php
  src/View/Actuality/index.html.twig
  src/View/Admin/index.html.twig
  src/View/Component/Admin/_navbar.html.twig
  src/View/Component/_navbar.html.twig
  src/View/Home/index.html.twig
  src/View/admin.html.twig
  src/View/base.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: REVIEWED

#12 Première version pour l'affichage du détail d'une actualité.
  public/assets/css/actuality.css
  src/Controller/ActualityController.php
  src/View/Actuality/show.html.twig
  src/View/Component/_card_actuality.html.twig
  src/routes.php
Labels: REVIEWED, CONFLICTS RESOLVED

#15 Modifier une actualité dans la partie administration
  src/Model/ActualityManager.php
  src/View/Admin/Actuality/edit.html.twig
  src/View/Component/_errors.html.twig
Labels: REVIEWED, CONFLICTS RESOLVED

#10 Livraison 3 dernières actualités sur page Home
  database.sql
  public/assets/css/actuality.css
  public/assets/css/actuality_small.css
  public/assets/css/header.css
  public/assets/css/navbar.css
  src/Controller/HomeController.php
  src/Model/ActualityManager.php
  src/View/Component/_card_actuality.html.twig
  src/View/Component/_card_actuality_home.html.twig
  src/View/Home/index.html.twig
  src/View/base.html.twig
  src/View/layout.html.twig
Labels: REVIEWED, CONFLICTS RESOLVED

#22 fix parent() dans block stylsheet
  src/View/Actuality/index.html.twig
  src/View/Actuality/show.html.twig
  src/View/Admin/Actuality/index.html.twig
  src/View/Beauceron/beauceron.html.twig
Labels: REVIEWED, CONFLICTS RESOLVED

#26 fix mauvaise route pour afficher le detail d'une actualité
  src/View/Component/_card_actuality.html.twig
  src/View/Component/_card_actuality_home.html.twig
Labels: REVIEWED

#31 Dev to Main Request
  .gitignore
  data_migration/adhesion-association.jpg
  data_migration/assemblee-generale.jpg
  data_migration/perte-audition-chien.webp
  database.sql
  migration.php
  public/assets/css/actuality.css
  public/assets/css/actuality_small.css
  public/assets/css/admin.css
  public/assets/css/caractere.css
  public/assets/css/errors.css
  public/assets/css/header.css
  public/assets/css/history.css
  public/assets/css/navbar.css
  public/assets/css/style.css
  public/assets/images/beauceron/beauceron1.jpeg
  public/assets/images/beauceron/beauceron2.jpg
  public/assets/images/beauceron/beauceron5.jpg
  public/assets/images/beauceron/empreinte.png
  public/assets/images/img_header_dog.jpg
  public/uploads/.gitignore
  src/Controller/AbstractController.php
  src/Controller/ActualityController.php
  src/Controller/Admin/AdminController.php
  src/Controller/AdminActualityController.php
  src/Controller/DogController.php
  src/Controller/HomeController.php
  src/Model/ActualityManager.php
  src/View/Actuality/index.html.twig
  src/View/Actuality/show.html.twig
  src/View/Admin/Actuality/_form.html.twig
  src/View/Admin/Actuality/add.html.twig
  src/View/Admin/Actuality/edit.html.twig
  src/View/Admin/Actuality/index.html.twig
  src/View/Admin/index.html.twig
  src/View/Beauceron/beauceron.html.twig
  src/View/Beauceron/beauceron_caractere.html.twig
  src/View/Component/Admin/_navbar.html.twig
  src/View/Component/_card_actuality.html.twig
  src/View/Component/_card_actuality_home.html.twig
  src/View/Component/_errors.html.twig
  src/View/Component/_navbar.html.twig
  src/View/Home/index.html.twig
  src/View/admin.html.twig
  src/View/base.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: REVIEWED

#5 start footer
  public/assets/css/footer.css
  public/assets/css/style.css
  public/assets/images/admin.png
  public/assets/images/pattes.png
  src/View/Component/_footer.html.twig
Labels: REVIEWED, CONFLICTS RESOLVED

#21 SQL table finish + view in articles
  database.sql
  public/assets/css/event.css
  public/assets/css/style.css
  public/assets/images/event/hotdogs.jpg
  public/assets/js/event.js
  src/Controller/EventController.php
  src/Model/EventManager.php
  src/View/Event/event.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: REVIEWED, CONFLICTS RESOLVED

#23 fix actuality css
  public/assets/css/actuality.css
  src/View/Actuality/index.html.twig
  src/View/Actuality/show.html.twig
  src/View/Component/_card_actuality.html.twig
Labels: REVIEWED, CONFLICTS RESOLVED

#33 fix the navbar
  public/assets/css/navbar.css
  src/View/Component/_navbar.html.twig
Labels: REVIEWED

#19 S01 us04 care
  public/assets/css/care.css
  public/assets/css/style.css
  public/assets/images/care/beauceron.png
  public/assets/images/care/clicherdifficulte.png
  public/assets/images/care/empreintechienblanc.png
  public/assets/images/care/empreintechiencontour.png
  public/assets/images/care/empreintelightcontour.png
  public/assets/images/care/femurbeauceron.png
  public/assets/images/care/laxiteArticulaire.png
  public/assets/images/care/mise-basBien.png
  public/assets/images/care/mise-basComplication.png
  public/assets/images/care/squelettebeauceron.png
  src/Controller/CareController.php
  src/View/Care/index.html.twig
  src/routes.php
Labels: REVIEWED, CONFLICTS RESOLVED

#24 fix admin twig layout et admin navbar link
  src/View/Admin/Actuality/add.html.twig
  src/View/Admin/Actuality/edit.html.twig
  src/View/Admin/Actuality/index.html.twig
  src/View/Component/Admin/_navbar.html.twig
  src/View/admin.html.twig
  src/View/layout.html.twig
Labels: REVIEWED, CONFLICTS RESOLVED

#25 Mise en place de la page de login
  database.sql
  public/assets/css/login.css
  public/index.php
  public/uploads/adhesion-association.jpg
  public/uploads/assemblee-generale.jpg
  public/uploads/perte-audition-chien.webp
  src/Controller/AbstractController.php
  src/Controller/LoginController.php
  src/Model/UserManager.php
  src/View/Login/login.html.twig
  src/routes.php
Labels: REVIEWED, CONFLICTS RESOLVED

#32 S03 u09 admin delete actuality
  src/Controller/AdminActualityController.php
  src/View/Admin/Actuality/index.html.twig
  src/routes.php
Labels: REVIEWED, CONFLICTS RESOLVED

#36 fix parent layout
  src/View/Care/index.html.twig
  src/View/Login/login.html.twig
Labels: REVIEWED

#38 fix url login button
  public/assets/css/header.css
  src/View/Home/index.html.twig
Labels: REVIEWED, CONFLICTS RESOLVED

#37 Request dev vers main
  database.sql
  public/assets/css/actuality.css
  public/assets/css/care.css
  public/assets/css/event.css
  public/assets/css/footer.css
  public/assets/css/genese.css
  public/assets/css/header.css
  public/assets/css/login.css
  public/assets/css/navbar.css
  public/assets/css/style.css
  public/assets/images/admin.png
  public/assets/images/beauceron/beauceron3.gif
  public/assets/images/beauceron/beauceron4.jpg
  public/assets/images/care/beauceron.png
  public/assets/images/care/clicherdifficulte.png
  public/assets/images/care/empreintechienblanc.png
  public/assets/images/care/empreintechiencontour.png
  public/assets/images/care/empreintelightcontour.png
  public/assets/images/care/femurbeauceron.png
  public/assets/images/care/laxiteArticulaire.png
  public/assets/images/care/mise-basBien.png
  public/assets/images/care/mise-basComplication.png
  public/assets/images/care/squelettebeauceron.png
  public/assets/images/event/hotdogs.jpg
  public/assets/images/pattes.png
  public/assets/js/event.js
  public/index.php
  public/uploads/adhesion-association.jpg
  public/uploads/assemblee-generale.jpg
  public/uploads/perte-audition-chien.webp
  src/Controller/AbstractController.php
  src/Controller/AdminActualityController.php
  src/Controller/CareController.php
  src/Controller/EventController.php
  src/Controller/LoginController.php
  src/Model/EventManager.php
  src/Model/UserManager.php
  src/View/Actuality/index.html.twig
  src/View/Actuality/show.html.twig
  src/View/Admin/Actuality/add.html.twig
  src/View/Admin/Actuality/edit.html.twig
  src/View/Admin/Actuality/index.html.twig
  src/View/Beauceron/beauceron.html.twig
  src/View/Beauceron/beauceron_genese.html.twig
  src/View/Care/index.html.twig
  src/View/Component/Admin/_navbar.html.twig
  src/View/Component/_card_actuality.html.twig
  src/View/Component/_footer.html.twig
  src/View/Component/_navbar.html.twig
  src/View/Event/event.html.twig
  src/View/Home/index.html.twig
  src/View/Login/login.html.twig
  src/View/admin.html.twig
  src/routes.php
Labels: REVIEWED

#29 liste des membres
  database.sql
  public/assets/images/profildefault.jpg
  src/Controller/AdminMemberController.php
  src/Model/MemberManager.php
  src/View/Admin/Member/index.html.twig
Labels: REVIEWED, CONFLICTS RESOLVED

#41 fix footer missing in layout
  src/View/Component/_footer.html.twig
  src/View/base.html.twig
  src/View/layout.html.twig
Labels: REVIEWED

#42 fix actualites home page style
  database.sql
  public/assets/css/actuality_small.css
  src/View/Component/_card_actuality_home.html.twig
  src/View/Home/index.html.twig
Labels: REVIEWED
